import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import rehypeRaw from "rehype-raw";
import remarkGfm from "remark-gfm";

import { getArticle } from "@/lib/api/get-article";
import { TableOfContents } from "@/components/table-of-contents";

type PageProps = {
  params: Promise<{ slug: string }>;
};

type Heading = {
  level: number;
  text: string;
  slug: string;
};

function slugify(value: string) {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function extractHeadings(markdown: string): Heading[] {
  const matches = Array.from(markdown.matchAll(/^#{1,6}\s+(.+)$/gm));
  const counts = new Map<string, number>();

  return matches.map((match) => {
    const rawText = match[1].trim();
    const level = Math.min(match[0].indexOf(" ") ?? 1, 6);
    const base = slugify(rawText);
    const currentCount = counts.get(base) ?? 0;
    counts.set(base, currentCount + 1);
    const slug = currentCount === 0 ? base : `${base}-${currentCount}`;

    return { level, text: rawText, slug };
  });
}

function enhanceCitations(markdown: string) {
  const refsMatch = markdown.match(/\n## References[\s\S]*$/);
  const references = refsMatch ? refsMatch[0] : "";
  const body = refsMatch
    ? markdown.slice(0, markdown.length - references.length)
    : markdown;

  const enhancedBody = body.replace(
    /\[(\d+)\]/g,
    (_, number: string) =>
      `<sup class="citation-marker" style="font-size:0.7em;"><a href="#ref-${number}">[${number}]</a></sup>`
  );

  const enhancedReferences = references
    ? references.replace(
        /\[(\d+)\]/g,
        (_, number: string) =>
          `<span id="ref-${number}" class="reference-label">[${number}]</span>`
      )
    : "";

  return enhancedBody + enhancedReferences;
}

export default async function ArticlePage({ params }: PageProps) {
  const article = await getArticle((await params).slug);

  if (!article) {
    notFound();
  }

  const formattedDate = article.publishedAt
    ? new Intl.DateTimeFormat("en", {
        dateStyle: "long",
      }).format(article.publishedAt)
    : null;

  const headings = extractHeadings(article.content);
  const tocHeadings = headings.filter((heading) => heading.level <= 3);
  const markdownWithCitations = enhanceCitations(article.content);
  let headingIndex = 0;

  return (
    <div className="mx-auto flex min-h-screen max-w-7xl gap-8 px-4 py-10 font-sans">
      <TableOfContents headings={tocHeadings} />

      <div className="flex-1 space-y-6">
        <header className="space-y-2">
          {formattedDate && (
            <p className="text-sm text-muted-foreground">
              Created by the Cognipedia Agent on {formattedDate}
            </p>
          )}
          <p className="text-sm text-muted-foreground">
            This article is generated by an LLM and may contain misinformation.
          </p>
        </header>

        <article className="prose prose-neutral max-w-none dark:prose-invert">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            rehypePlugins={[rehypeRaw]}
            components={{
              a({ children, href, ...props }) {
                if (!href) return <span {...props}>{children}</span>;
                const isExternal = /^https?:\/\//.test(href);
                return (
                  <a
                    href={href}
                    target={isExternal ? "_blank" : undefined}
                    rel={isExternal ? "noreferrer" : undefined}
                    {...props}
                    className="text-blue-600 hover:underline"
                  >
                    {children}
                  </a>
                );
              },
              h1({ children, ...props }) {
                const heading = tocHeadings[headingIndex++];
                return (
                  <h1
                    id={heading?.slug}
                    {...props}
                    className="mb-4 text-3xl font-semibold"
                  >
                    {children}
                  </h1>
                );
              },
              h2({ children, ...props }) {
                const heading = tocHeadings[headingIndex++];
                return (
                  <h2
                    id={heading?.slug}
                    {...props}
                    className="mb-3 mt-6 text-2xl font-semibold"
                  >
                    {children}
                  </h2>
                );
              },
              h3({ children, ...props }) {
                const heading = tocHeadings[headingIndex++];
                return (
                  <h3
                    id={heading?.slug}
                    {...props}
                    className="mb-2 mt-4 text-xl font-semibold"
                  >
                    {children}
                  </h3>
                );
              },
            }}
          >
            {markdownWithCitations}
          </ReactMarkdown>
        </article>
      </div>
    </div>
  );
}
