import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import rehypeRaw from "rehype-raw";
import remarkGfm from "remark-gfm";

import { getArticle } from "@/lib/api/get-article";

type PageProps = {
  params: Promise<{ slug: string }>;
};

function enhanceCitations(markdown: string) {
  const refsMatch = markdown.match(/\n## References[\s\S]*$/);
  const references = refsMatch ? refsMatch[0] : "";
  const body = refsMatch
    ? markdown.slice(0, markdown.length - references.length)
    : markdown;

  const enhancedBody = body.replace(
    /\[(\d+)\]/g,
    (_, number: string) =>
      `<sup class="citation-marker" style="font-size:0.75em;vertical-align:super;"><a href="#ref-${number}">[${number}]</a></sup>`
  );

  const enhancedReferences = references
    ? references.replace(
        /\[(\d+)\]/g,
        (_, number: string) =>
          `<span id="ref-${number}" class="reference-label">[${number}]</span>`
      )
    : "";

  return enhancedBody + enhancedReferences;
}

export default async function ArticlePage({ params }: PageProps) {
  const article = await getArticle((await params).slug);

  if (!article) {
    notFound();
  }

  const formattedDate = article.publishedAt
    ? new Intl.DateTimeFormat("en", {
        dateStyle: "long",
      }).format(article.publishedAt)
    : null;

  const markdownWithCitations = enhanceCitations(article.content);

  return (
    <div className="mx-auto flex min-h-screen max-w-7xl flex-col gap-6 px-4 py-10 font-sans">
      <header className="space-y-2">
        {formattedDate && (
          <p className="text-sm text-muted-foreground">
            Created by the Cognipedia Agent on {formattedDate}
          </p>
        )}
        <p className="text-sm text-muted-foreground">
          This article is generated by an LLM and may contain misinformation.
        </p>
      </header>

      <article className="prose prose-neutral max-w-none dark:prose-invert">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          rehypePlugins={[rehypeRaw]}
          components={{
            a({ children, href, ...props }) {
              if (!href) return <span {...props}>{children}</span>;
              const isExternal = /^https?:\/\//.test(href);
              return (
                <a
                  href={href}
                  target={isExternal ? "_blank" : undefined}
                  rel={isExternal ? "noreferrer" : undefined}
                  {...props}
                  className="hover:underline text-blue-600"
                >
                  {children}
                </a>
              );
            },
            h1({ children, ...props }) {
              return (
                <h1 {...props} className="text-3xl font-semibold mb-4">
                  {children}
                </h1>
              );
            },
            h2({ children, ...props }) {
              return (
                <h2 {...props} className="text-2xl font-semibold mb-3">
                  {children}
                </h2>
              );
            },
            h3({ children, ...props }) {
              return (
                <h3 {...props} className="text-xl font-semibold mb-2">
                  {children}
                </h3>
              );
            },
            p({ children, ...props }) {
              return (
                <p {...props} className="text-base mb-3">
                  {children}
                </p>
              );
            },
          }}
        >
          {markdownWithCitations}
        </ReactMarkdown>
      </article>
    </div>
  );
}
